name: app
description: "GNext logistic application"

publish_to: 'none'

version: 4.1.0+5.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  responsive_sizer: ^3.3.0+1
  pinput: ^4.0.0
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_slider_drawer: ^2.1.3
  buttons_tabbar: ^1.3.8
  firebase_core: ^2.27.0
  flutter_chat_bubble: ^2.0.2
  firebase_auth: ^4.17.8
  retrofit: '>=4.0.0 <5.0.0'
  json_annotation: ^4.8.1
  motion_toast: ^2.8.0
  firebase_messaging: ^14.7.19
  image_picker: ^1.0.7
  socket_io_client: ^2.0.3+1
  animated_custom_dropdown: ^3.0.0
  address_search_field: ^4.0.1
  bottom_picker: ^2.4.0
  dio: ^5.4.1
  geocoding: ^3.0.0
  story: ^1.1.0
  video_player: ^2.8.3
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  flutter_file_downloader: ^1.2.1
  fluttertoast: ^8.2.4
  permission_handler: ^11.2.0
  shared_preferences: ^2.2.2
  voice_message_package: ^2.1.4
  audio_waveforms: ^1.0.5
  device_info_plus: ^10.0.1
  flutter_paypal_payment: ^1.0.6
  currency_converter: ^0.0.4
  flutter_bloc: ^7.0.0

icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      image_path: 'assets/icon_border.png'
      adaptive_background_image: 'assets/background.png'
      adaptive_foreground_image: 'assets/icon_foregraund.png'
      adaptive_round_image: 'assets/icon_round.png'
      enable: true
    ios:
      enable: true
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  retrofit_generator: ^8.1.0
  icons_launcher: ^2.1.7
flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: ru